ModLoader.SetupFileHook( "lua/TargetCache.lua", "lua/TargetCache_Siege.lua", "post" )
ModLoader.SetupFileHook( "lua/GameInfo.lua", "lua/GameInfo_Siege19.lua", "post" )
--------Timer GUI---------
ModLoader.SetupFileHook( "lua/Hud/GUIPlayerResource.lua", "lua/doors/gui/GUIPlayerResource_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/Hud/Marine/GUIMarineHUD.lua", "lua/doors/gui/GUIMarineHUD_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/GUIInsight_TopBar.lua", "lua/doors/gui/GUIInsight_TopBar_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/GUIAlienHUD.lua", "lua/doors/gui/GUIAlienHUD_Siege22.lua", "post" )
-----------------------
ModLoader.SetupFileHook( "lua/shine/core/shared/hook.lua", "lua/shine/hook.lua", "post" )
ModLoader.SetupFileHook( "lua/Location.lua", "lua/Location_Siege.lua", "post" )
ModLoader.SetupFileHook( "lua/Globals.lua", "lua/Globals_Siege19.lua", "post" ) 
ModLoader.SetupFileHook( "lua/NS2Gamerules.lua", "lua/NS2Gamerules_Siege19.lua", "post" )
ModLoader.SetupFileHook( "lua/TechData.lua", "lua/TechData_Siege22.lua", "post" ) 
ModLoader.SetupFileHook( "lua/Balance.lua", "lua/Balance_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/BalanceMisc.lua", "lua/BalanceMisc_Siege22.lua", "post" )
---------------Player------------
ModLoader.SetupFileHook( "lua/Marine.lua", "lua/player/Marine_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/Alien.lua", "lua/player/Alien_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/Skulk.lua", "lua/player/Skulk_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/Lerk.lua", "lua/player/Lerk_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/Fade.lua", "lua/player/Fade_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/Gorge.lua", "lua/player/Gorge_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/Player_Client.lua", "lua/player/Player_Client_Siege19.lua", "post" )
-------Mixins----
ModLoader.SetupFileHook( "lua/SupplyUserMixin.lua", "lua/Modifications/SupplyUserMixin_Siege.lua", "post" )
ModLoader.SetupFileHook( "lua/PhaseGateUserMixin.lua", "lua/Modifications/PhaseGateUserMixin_Siege22.lua", "post" )

--------------
ModLoader.SetupFileHook( "lua/CommAbilities/Alien/Contamination.lua", "lua/Modifications/Contamination.lua", "post" )
ModLoader.SetupFileHook( "lua/Server.lua", "lua/Server_Siege.lua", "post" )
ModLoader.SetupFileHook( "lua/Alien_Upgrade.lua", "lua/Alien_Upgrade_Siege20.lua", "post" )
ModLoader.SetupFileHook( "lua/TechTreeButtons.lua", "lua/TechTreeButtons_Siege19.lua", "post" )
ModLoader.SetupFileHook( "lua/TechTreeConstants.lua", "lua/TechTreeConstants_Siege19.lua", "post" )
ModLoader.SetupFileHook( "lua/AlienTeam.lua", "lua/AlienTeam_Siege22.lua", "post" )
--ModLoader.SetupFileHook( "lua/AlienWeaponEffects.lua", "lua/AlienWeaponEffects_Siege.lua", "post" )
ModLoader.SetupFileHook( "lua/InputHandler.lua", "lua/InputHandler_Siege.lua", "post" )
ModLoader.SetupFileHook( "lua/TechNode.lua", "lua/TechNode_Siege.lua", "post" )
ModLoader.SetupFileHook( "lua/NS2Utility_Server.lua", "lua/NS2Utility_Server_Siege20.lua", "post" )
ModLoader.SetupFileHook( "lua/GUIAlienBuyMenu.lua", "lua/GUIAlienBuyMenu_Siege20.lua", "post" )--override
ModLoader.SetupFileHook( "lua/Weapons/Marine/Flamethrower.lua", "lua/Weapons/Marine/Flamethrower_Siege.lua", "post" )

-------------------------Structures---------------
ModLoader.SetupFileHook( "lua/Clog.lua", "lua/structures/Clog_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/ARC.lua", "lua/structures/ARC_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/MAC.lua", "lua/structures/MAC_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/Armory.lua", "lua/structures/Armory_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/Observatory.lua", "lua/structures/Observatory_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/Sentry.lua", "lua/structures/Sentry_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/SentryBattery.lua", "lua/structures/SentryBattery_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/PhaseGate.lua", "lua/structures/PhaseGate_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/InfantryPortal.lua", "lua/structures/InfantryPortal_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/RoboticsFactory.lua", "lua/structures/RoboticsFactory_Siege22.lua", "post" ) 
ModLoader.SetupFileHook( "lua/Crag.lua", "lua/structures/Crag_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/Whip.lua", "lua/structures/Whip_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/Shift.lua", "lua/structures/Shift_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/Shade.lua", "lua/structures/Shade_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/Hydra.lua", "lua/structures/Hydra_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/Hive.lua", "lua/structures/Hive_Siege22.lua", "post" )
ModLoader.SetupFileHook( "lua/TunnelEntrance.lua", "lua/structures/TunnelEntrance_Siege22.lua", "post" )
