kIntervalForArcsDuringSiege = 8
kMarineBuffInterval = 16
kManageMacInterval = 12 -- maybe better to have the manage mac inside the mac lua and tell it there to manage itself. hm?
kManageArcInterval = 4
kManageScanInterval = 9
kManageDrifterInterval = 11
kManageShadeInterval = 16
kManageCragInterval = 17
kManageShiftsInterval = 18
kManageWhipsInterval = 19
kManageCystsInterval = 20
kResTowerInterval = 30 -- well if setup then .. bleh